kind: pipeline
name: default

steps:
  - name: build
    image: kkarczmarczyk/node-yarn:latest
    commands:
      - yarn install
      - yarn build

  - name: publish
    image: plugins/docker
    repo: veiasai/bookstore-front
    tags: ["latest", "v1"]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile