workspace:
  base: /front
  path: src/github.com/veiasai/front
pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run-script build
  publish:
    image: plugins/docker
    repo: veiasai/bookstore-front
    tags: ["latest", "v2"]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile